### ISSUE TITLE
현재 이 레포가 관리되고 있나요?

### ISSUE THREAD

**Issue by bossm0n5t3r** [funfunStory/fp-kotlin-example#11]
확인된 이슈 편하게 올려도 될까요?

**Comment by goinhacker** [comment]
PR 주시면 리뷰후 반영할겠습니다.

2022년 12월 13일 (화) 오전 1:08, bossm0n5t3r ***@***.***>님이 작성:

**Comment by bossm0n5t3r** [comment]
넵 확인 감사합니다! 이 이슈는 닫도록 할께요 🙇
